---
# akoi - binary version control system
# https://github.com/suzuki-shunsuke/akoi
bin_path: .akoi/bin/{{.Name}}-{{.Version}}
link_path: .akoi/bin/{{.Name}}
packages:
  circleci-config-merge:
    url: 'https://github.com/suzuki-shunsuke/{{.Name}}/releases/download/{{.Version}}/{{.Name}}_{{trimPrefix "v" .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
    version: v0.1.4  # renovate: depName=suzuki-shunsuke/circleci-config-merge
    files:
      - name: circleci-config-merge
        archive: "{{.Name}}"
  dyff:
    url: "https://github.com/homeport/dyff/releases/download/{{.Version}}/dyff-{{.OS}}-{{.Arch}}"
    version: v1.1.3  # renovate: depName=homeport/dyff
    archive_type: unarchived
    files:
      - name: dyff
        archive: "dyff-{{.OS}}-{{.Arch}}"
  github-comment:
    url: 'https://github.com/suzuki-shunsuke/{{.Name}}/releases/download/{{.Version}}/{{.Name}}_{{trimPrefix "v" .Version}}_{{.OS}}_{{.Arch}}.tar.gz'
    version: v6.0.4 # renovate: depName=suzuki-shunsuke/github-comment
    files:
      - name: github-comment
        archive: "{{.Name}}"
