# Don't edit .circleci/config.yml directly!
# .circleci/config.yml is being split per service.
# If you want to update .circleci/config.yml, update split files and run
#
# $ make circleci
#
# and commit split files and .circleci/config.yml.
# This header comment is managed at scripts/circleci-config-header-comment.txt.
#
commands:
  bar:
    steps:
    - run:
        command: echo bar
        name: bar
  foo:
    steps:
    - run:
        command: echo foo
        name: foo
executors:
  bar:
    docker:
    - image: alpine:3.11.6
  foo:
    docker:
    - image: alpine:3.11.6
jobs:
  bar:
    executor: bar
    steps:
    - bar
  foo:
    executor: foo
    steps:
    - foo
  test-circleci-config:
    docker:
    - image: alpine:3.12.1
    steps:
    - run:
        command: apk add ca-certificates bash git curl
        name: setup
    - checkout
    - run:
        command: bash ci/test-circleci-config.sh
        name: test .circleci/config.yml
version: "2.1"
workflows:
  bar:
    jobs:
    - bar
  build:
    jobs:
    - bar
    - foo
    - test-circleci-config
  foo:
    jobs:
    - foo
